Compute inverse dynamics partials via finite differences
vincekurtz/drake pull request #17
Opened 2022-07-26 20:57 UTC by vincekurtz

Calculates the partial derivatives of generalized forces `tau_t(q_{t-1}, q_t, q_{t+1})`, with respect to generalized positions `q_t` (our decision variables) using finite differences.

This is not a very efficient implementation, but should give us a place to start for constructing gradients and Hessians.

2022-07-26 20:59 UTC, vincekurtz reviewed
+@amcastro-tri for feature review please

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/17#-:-N7wILQi2pC91GEsK500:brbsdox)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @amcastro-tri)



<!-- Sent from Reviewable.io -->

2022-07-26 22:28 UTC, amcastro-tri requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/17)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/problem_data.h` line 27 at r1](https://reviewable.io/reviews/vincekurtz/drake/17#-N7wabPx7BS0_LB8_CpT:-N7wabPx7BS0_LB8_CpU:b-iyau0f) ([raw file](https://github.com/vincekurtz/drake/blob/e153e0ad46d767f071fdae3634b341e0efbacad8/traj_opt/problem_data.h#L27)):*
> ```objc
>   //    [ 0, d(tau_0)/d(q_1), d(tau_1)/d(q_2), ... ,
>   //                                     d(tau_{num_steps-1})/d(q_{num_steps})]
>   std::vector<MatrixXd> dtaum_dq;
> ```

Lets use banded format here, where if I take these three vector, say A B C and I index then with t, as in A[t], B[t], C[t], then I'd be looking at the t-th row.

Our notation for a row in dtau_dq then would read dtau_dqm[t], dtau_dq[t], dtaum_dqp[t]
___
*[`traj_opt/trajectory_optimizer.h` line 132 at r1](https://reviewable.io/reviews/vincekurtz/drake/17#-N7wSsJV70O1EYbRjD5E:-N7wSsJV70O1EYbRjD5F:bbycnay) ([raw file](https://github.com/vincekurtz/drake/blob/e153e0ad46d767f071fdae3634b341e0efbacad8/traj_opt/trajectory_optimizer.h#L132)):*
> ```objc
>    */
>   void CalcInverseDynamicsPartialsFiniteDiff(const std::vector<VectorXd>& q,
>                                              const std::vector<VectorXd>& v,
> ```

nit, if the final intent is for the user to never call this method but instead to call CalcInverseDynamicsPartials(), consider making this one method private?
___
*[`traj_opt/trajectory_optimizer.cc` line 85 at r1](https://reviewable.io/reviews/vincekurtz/drake/17#-N7wTMoy0o2jx0_e8yAw:-N7wTMoy0o2jx0_e8yAx:b-u4y2rl) ([raw file](https://github.com/vincekurtz/drake/blob/e153e0ad46d767f071fdae3634b341e0efbacad8/traj_opt/trajectory_optimizer.cc#L85)):*
> ```cpp
>   // Allocate storage space
>   // TODO(vincekurtz): allocate a GradientData struct of the proper size earlier
>   // in the process, and check that it has the correct size here.
> ```

resolve this TODO in this PR, we definitely do not want to allocate memory on the flight in any of this code.
For instance, have a `Resize()` method in your `GradientData` and a `size()` method that retuns its size. Here you could `DRAKE_DEMAND(grad_data->size() == num_steps())` to enforce the proper size at input.
___
*[`traj_opt/trajectory_optimizer.cc` line 103 at r1](https://reviewable.io/reviews/vincekurtz/drake/17#-N7wTxxEE08gg_RGm9MG:-N7wTxxEE08gg_RGm9MH:b-37uc66) ([raw file](https://github.com/vincekurtz/drake/blob/e153e0ad46d767f071fdae3634b341e0efbacad8/traj_opt/trajectory_optimizer.cc#L103)):*
> ```cpp
>   VectorXd a(plant().num_velocities());    // scratch space
>   MultibodyForces<double> f_ext(plant());  // scratch space
>   std::vector<VectorXd> tau(num_steps());
> ```

It'd seem this combination is very common as we already encountered it when computing inverse dynamics. I imagine other variables will add later on.
I propose that any of this methods should not allocate. Allocations are expensive, particularly at this level. 
Something you could do is to have a `struct` called `TrajectoryOptimizerWorkspace` where you place these and other variables you might need to perform computations. Then this method takes a `TrajectoryOptimizerWorkspace`  that can be mutated at will. The calling code is responsible for allocating this struct properly before the call (again, you can have the nice pair `Resize()` + `size()` to provide some basic enforcement of this).
___
*[`traj_opt/trajectory_optimizer.cc` line 111 at r1](https://reviewable.io/reviews/vincekurtz/drake/17#-N7wUp0RC1hy2NtOq81W:-N7wUp0RC1hy2NtOq81X:brpntwk) ([raw file](https://github.com/vincekurtz/drake/blob/e153e0ad46d767f071fdae3634b341e0efbacad8/traj_opt/trajectory_optimizer.cc#L111)):*
> ```cpp
>   std::vector<VectorXd> tau_eps(tau);
> 
>   const double eps = sqrt(std::numeric_limits<double>::epsilon());
> ```

check the Numerical Recipies book. I belive using machine epsilon  actually degrades the actual precision. What you want here is something like `sqrt(eps)` instead for the "optimal" epsilon that leads to the best results.


<!-- Sent from Reviewable.io -->

2022-07-27 15:47 UTC, vincekurtz reviewed
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/17)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @amcastro-tri)

___
*[`traj_opt/problem_data.h` line 27 at r1](https://reviewable.io/reviews/vincekurtz/drake/17#-N7wabPx7BS0_LB8_CpT:-N7wtgRHCLFaljrEkKuW:b3oh8n) ([raw file](https://github.com/vincekurtz/drake/blob/e153e0ad46d767f071fdae3634b341e0efbacad8/traj_opt/problem_data.h#L27)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Lets use banded format here, where if I take these three vector, say A B C and I index then with t, as in A[t], B[t], C[t], then I'd be looking at the t-th row.

Our notation for a row in dtau_dq then would read dtau_dqm[t], dtau_dq[t], dtaum_dqp[t]


</blockquote></details>


Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 85 at r1](https://reviewable.io/reviews/vincekurtz/drake/17#-N7wTMoy0o2jx0_e8yAw:-N8-JYwE7sHrS5M3tN56:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/e153e0ad46d767f071fdae3634b341e0efbacad8/traj_opt/trajectory_optimizer.cc#L85)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

resolve this TODO in this PR, we definitely do not want to allocate memory on the flight in any of this code.
For instance, have a `Resize()` method in your `GradientData` and a `size()` method that retuns its size. Here you could `DRAKE_DEMAND(grad_data->size() == num_steps())` to enforce the proper size at input.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 103 at r1](https://reviewable.io/reviews/vincekurtz/drake/17#-N7wTxxEE08gg_RGm9MG:-N8-40V20M_AeUt8eSzW:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/e153e0ad46d767f071fdae3634b341e0efbacad8/traj_opt/trajectory_optimizer.cc#L103)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

It'd seem this combination is very common as we already encountered it when computing inverse dynamics. I imagine other variables will add later on.
I propose that any of this methods should not allocate. Allocations are expensive, particularly at this level. 
Something you could do is to have a `struct` called `TrajectoryOptimizerWorkspace` where you place these and other variables you might need to perform computations. Then this method takes a `TrajectoryOptimizerWorkspace`  that can be mutated at will. The calling code is responsible for allocating this struct properly before the call (again, you can have the nice pair `Resize()` + `size()` to provide some basic enforcement of this).
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 111 at r1](https://reviewable.io/reviews/vincekurtz/drake/17#-N7wUp0RC1hy2NtOq81W:-N7wgqHx3vdcOgAAKzJ-:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/e153e0ad46d767f071fdae3634b341e0efbacad8/traj_opt/trajectory_optimizer.cc#L111)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

check the Numerical Recipies book. I belive using machine epsilon  actually degrades the actual precision. What you want here is something like `sqrt(eps)` instead for the "optimal" epsilon that leads to the best results.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-27 19:51 UTC, amcastro-tri requested changes
> Reviewed 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/17)* status: 4 of 6 files reviewed, 10 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/problem_data.h` line 15 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N80-6S23gTXYI1HlUH1:-N80-6S23gTXYI1HlUH2:b3tw3sr) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L15)):*
> used to compute the (approximate) gradient and Hessian for our Gauss-Newton

Is this true? I thought the purpose of this class was to store dtau_dq only, my preference, though of course I can be convinced otherwise.



_Code quote:_
```objc
 * Struct containing the gradients of key dynamics terms that are used to
 * compute the (approximate) gradient and Hessian for our Gauss-Newton steps.
```
___
*[`traj_opt/problem_data.h` line 31 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N800naq2wv9ypSEMqwG:-N800naq2wv9ypSEMqwH:bjd1p3o) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L31)):*
> dtau_dq[0].setZero();

thinking....
Is this true? u_0 I believe is a function of q_0 just fine. We do have the boundary condition q_0=q_init (first set of equations) but the second equations should encode this dependence implicitly?
___
*[`traj_opt/problem_data.h` line 32 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N800gZh4VJKtoMYqWjV:-N800gZh4VJKtoMYqWjW:bvfuskl) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L32)):*
> ```objc
>     // Set all derivatives w.r.t q(0) and q(-1) to zero
>     dtau_dq[0].setZero();
>     dtau_dqm[0].setZero();
> ```

is this one ever used? if not, I'd initialize to NaN so that we get a trail of crumbs if we happen to use it by mistake.



_Code quote:_
```objc
dtau_dqm[0]
```
___
*[`traj_opt/problem_data.h` line 33 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N801_Zv-RDVohxtjsTd:-N801_Zv-RDVohxtjsTe:br40zk) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L33)):*
> ```objc
>     dtau_dq[0].setZero();
>     dtau_dqm[0].setZero();
>     dtau_dqm[1].setZero();
> ```

this ones is more mysterious to me yet.
___
*[`traj_opt/problem_data.h` line 41 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N801k9CE6p2NMkPC4LF:-N801k9CE6p2NMkPC4LG:b-p66s9z) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L41)):*
> ```objc
>   int size() const {
>     DRAKE_DEMAND(dtau_dq.size() == dtau_dqm.size());
>     DRAKE_DEMAND(dtau_dq.size() == dtau_dqp.size());
> ```

these checks do not belong here. If you are worried about someone trashing one of the arrays then maybe worth making this a class so that the only way to build it poperly is through its constructor.
___
*[`traj_opt/problem_data.h` line 50 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N8024pM94dS6c5GZhpm:-N8024pM94dS6c5GZhpn:b-4buqyn) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L50)):*
> ```objc
>   //
>   // for each timestep. This is indexed by t ranging from 0 to num_steps-1.
>   // For values where tau_t or q_{t-1} is undefined or constant, we simply store
> ```

for undefined values I recommend storing NaN, for the reasons I commented above.
___
*[`traj_opt/trajectory_optimizer.h` line 145 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N803gyu8aH2jaFFnqnI:-N803gyv6gFl5ACgHZX5:b-c3myhu) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/trajectory_optimizer.h#L145)):*
> ```objc
>    * where
>    *
>    *    a = (v_next - v) / dt
> ```

minor, IMO, per your math above, it looks neater if you pass `a` instead of `v_next` and you just let the caller decide how that acceleration is approximated (or not).
___
*[`traj_opt/trajectory_optimizer.cc` line 111 at r1](https://reviewable.io/reviews/vincekurtz/drake/17#-N7wUp0RC1hy2NtOq81W:-N809EZCEd7E6jtn95pk:b-kk03fb) ([raw file](https://github.com/vincekurtz/drake/blob/e153e0ad46d767f071fdae3634b341e0efbacad8/traj_opt/trajectory_optimizer.cc#L111)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry!
___
*[`traj_opt/trajectory_optimizer.cc` line 71 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N808J8x7ITRqrlXI2vd:-N808J8x7ITRqrlXI2ve:b-2pbqmt) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/trajectory_optimizer.cc#L71)):*
> ```cpp
>   // CalcInverseDynamics considers damping from v_t (D*v_t), but we want to
>   // consider damping from v_{t+1} (D*v_{t+1}).
>   tau->array() += joint_damping_.array() * (v_next.array() - v.array());
> ```

per f2f, lets write the inverse dynamics as a function of qt, vt, at, all evaluated at the "current step", since in traj opt there is no real gain on using the "previous step". Actually, that might be counterproductive given that evaluating things at q_{t-1} could introduce strong off-diagonal terms that I'm pretty certain will make things unstable. In sim, we cannot do this simply because we don't know how to do it (as in SAP) or because it's too expensive. But we'd do it if we could! it is well known that doing so would increase stability significantly.
Therefore, if this does not cost us anything and simplifies coding, we should do it. 



_Code quote:_
```cpp
  tau->array() += joint_damping_.array() * (v_next.array() - v.array());
```
___
*[`traj_opt/trajectory_optimizer.cc` line 98 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N808z0-A0HB79no_zMo:-N808z0-A0HB79no_zMp:br2uwc3) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/trajectory_optimizer.cc#L98)):*
> ```cpp
>   // TODO(vincekurtz): consider passing this as an argument along with q and v,
>   // perhaps combined into a TrajectoryData struct
>   std::vector<VectorXd> tau(num_steps());
> ```

should this come form the workspace?
___
*[`traj_opt/trajectory_optimizer.cc` line 116 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N809yYmBx0LaO48xe6l:-N809yYmBx0LaO48xe6m:bvtwnqh) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/trajectory_optimizer.cc#L116)):*
> ```cpp
>       // Perturb q_t by epsilon
>       q_eps_t = q[t];
>       q_eps_t(i) += eps;
> ```

per f2f (yesterday) here we'd probably like:
```c++
dqt_i = eps * max(1.0, abs(q_eps_t(i)));  // so that we don't loose precision due to finite precision arithmetic.
qt_eps(i) += dqt_i;
```



_Code quote:_
```cpp
 q_eps_t(i) += eps;
```
___
*[`traj_opt/trajectory_optimizer_workspace.h` line 48 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N802T9t-c9fjHOToiZr:-N802T9t-c9fjHOToiZs:b-judt68) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/trajectory_optimizer_workspace.h#L48)):*
> ```objc
>   VectorXd tau_eps_tm;
>   VectorXd tau_eps_t;
>   VectorXd tau_eps_tp;
> ```

fyi, this is ok but you can also store a bunch of temp variables here that then you alias in your code to make it pretty. 

For instance, if you had:
```c++
struct  TrajectoryOptimizerWorkspace {
  // Storage of size nv.
  VectorXd v_size_temp1;
  VectorXd v_size_temp2;
  // Storage of size nq.
  VectorXd q_size_temp1;
  VectorXd q_size_temp2;
  // Storage for multibody forces
  MultibodyForces<double> mpb_forces_temp1;
  // etc. other sizes and types.
};
```

then your code could look like:
```c++
    // These aliases cost nothing in C++. 
    VectorXd& qt = workspace.q_size_temp1;
    VectorXd& qt_eps = workspace.q_size_temp2;
```

Anyway, the bottom line is that in principle you wouldn't need a n [...]

2022-07-27 23:48 UTC, vincekurtz reviewed
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/17)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @amcastro-tri)

___
*[`traj_opt/problem_data.h` line 15 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N80-6S23gTXYI1HlUH1:-N80yfq-0DfgUfZNIBrg:baxt8lg) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L15)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> used to compute the (approximate) gradient and Hessian for our Gauss-Newton

Is this true? I thought the purpose of this class was to store dtau_dq only, my preference, though of course I can be convinced otherwise.
</blockquote></details>

I'm thinking that `dv/dq` crops up in a lot of the same places as `dtau/dq` in the computation of the gradient and Hessian, so probably that (or some objects with a `MultiplyByDvDq` sort of method) end up here. 

I'd be fine having this store just `dtau/dq`, but would want to give it a more specific name in that case, maybe something like `InverseDynamicsGradientData`. 

Per f2f I'll wait until more of the code is flushed out to make any decisions in that regard.  
___
*[`traj_opt/problem_data.h` line 31 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N800naq2wv9ypSEMqwG:-N810OF6AbmvDYZ7N7pE:b2l2fvr) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L31)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

> dtau_dq[0].setZero();

thinking....
Is this true? u_0 I believe is a function of q_0 just fine. We do have the boundary condition q_0=q_init (first set of equations) but the second equations should encode this dependence implicitly?
</blockquote></details>

I was thinking that all derivatives w.r.t. q_0 get overwritten by zeros anyway, so we could just set them to zero. But I now think this may be wrong, so updated the code accordingly. 
___
*[`traj_opt/problem_data.h` line 32 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N800gZh4VJKtoMYqWjV:-N810mml1DiCnDsFwpfu:b-l2yru0) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L32)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

is this one ever used? if not, I'd initialize to NaN so that we get a trail of crumbs if we happen to use it by mistake.
</blockquote></details>

Done, good call. 
___
*[`traj_opt/problem_data.h` line 33 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N801_Zv-RDVohxtjsTd:-N810quaAEdnzLCFuBQ6:ba1ca7x) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L33)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this ones is more mysterious to me yet.
</blockquote></details>

This is `dtau(t)/dq(t-1)`. Per comment above I was thinking `[anything]/dq(0) = 0` but this may be wrong. Fixed and computed properly now. 
___
*[`traj_opt/problem_data.h` line 41 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N801k9CE6p2NMkPC4LF:-N811FzO93IlcYN-W0ux:bpfan3u) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L41)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

these checks do not belong here. If you are worried about someone trashing one of the arrays then maybe worth making this a class so that the only way to build it poperly is through its constructor.
</blockquote></details>

Good to know. Making this a class is probably the right way technically, but I'll leave it as a struct for now b/c laziness. 
___
*[`traj_opt/problem_data.h` line 50 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N8024pM94dS6c5GZhpm:-N811ynfArZoA3ZIh3qo:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L50)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

for undefined values I recommend storing NaN, for the reasons I commented above.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 71 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N808J8x7ITRqrlXI2vd:-N80wvU79Art0RX-s1lR:ba5d5bo) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/trajectory_optimizer.cc#L71)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

per f2f, lets write the inverse dynamics as a function of qt, vt, at, all evaluated at the "current step", since in traj opt there is no real gain on using the "previous step". Actually, that might be counterproductive given that evaluating things at q_{t-1} could introduce strong off-diagonal terms that I'm pretty certain will make things unstable. In sim, we cannot do this simply because we don't know how to do it (as in SAP) or because it's too expensive. But we'd do it if we could! it is well known that doing so would increase stability significantly.
Therefore, if this does not cost us anything and simplifies coding, we should do it. 
</blockquote></details>

Done, at the cost of some additional messy notation in `CalcInverseDynamicsPartialsFiniteDiff`. If you can see any way that can be made neater that would be awesome. 

Otherwise, it does make `InverseDynamicsHelper` a lot cleaner and I now agree is the right way to go.

N.B. This formulation (`tau[t] = M(q[t+1])a[t] + k(q[t+1],v[t+1])...`) changes a bunch of the math that we wrote out on overleaf. I wrote a remark to that effect there, but have not gone through and updated everything.
___
*[`traj_opt/trajectory_optimizer.cc` line 98 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N808z0-A0HB79no_zMo:-N80KMUqB2bgw-TX49NE:b-rp8eu9) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/trajectory_optimizer.cc#L98)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

should this come form the workspace?
</blockquote></details>

I think it's not worth it for now. Eventually, when `CalcInverseDynamicsPartials` gets called, I believe we will have already computed `q`, `v(q)`, and `tau(q)`. Either for the total cost `L(q)`, the gradient/Hessian, or something else. So I think the better solution would be to pass `tau` as an argument (probably inside some struct), per the TODO in the comment above. 
___
*[`traj_opt/trajectory_optimizer.cc` line 116 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N809yYmBx0LaO48xe6l:-N80K5Nf2np2SQsqMuWW:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/trajectory_optimizer.cc#L116)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

per f2f (yesterday) here we'd probably like:
```c++
dqt_i = eps * max(1.0, abs(q_eps_t(i)));  // so that we don't loose precision due to finite precision arithmetic.
qt_eps(i) += dqt_i;
```
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer_workspace.h` line 48 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N802T9t-c9fjHOToiZr:-N80GncRC6pEOosEVSC6:b-fznogt) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/trajectory_optimizer_workspace.h#L48)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

fyi, this is ok but you can also store a bunch of temp variables here that then you alias in your code to make it pretty. 

For instance, if you had:
```c++
struct  TrajectoryOptimizerWorkspace {
  // Storage of si [...]

2022-07-28 14:47 UTC, amcastro-tri requested changes
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/17)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/problem_data.h` line 41 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N801k9CE6p2NMkPC4LF:-N844GpoENkLc1OvDE66:bb73djm) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/problem_data.h#L41)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Good to know. Making this a class is probably the right way technically, but I'll leave it as a struct for now b/c laziness. 
</blockquote></details>

SGTM
___
*[`traj_opt/problem_data.h` line 35 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N844Mky3l5Sj_3Y1b4g:-N844Mky3l5Sj_3Y1b4h:b-8tjto2) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/problem_data.h#L35)):*
> ```objc
>         dtau_dqm[0](i, j) = NAN;
>       }
>     }
> ```

nit, you can do `dtau_dqm[0].setConstant(nv, nq, NAN)`
___
*[`traj_opt/problem_data.h` line 37 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N844gba0YPJB3XyA59j:-N844gbbEYY2LsUoBNNU:bcceap0) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/problem_data.h#L37)):*
> ```objc
>     }
>   }
> ```

Following the train of thought for dtau_dqm[0], should we also do `dtau_dqp[num_steps-1].setConstant(nv, nq, NAN)`?
___
*[`traj_opt/problem_data.h` line 64 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N845A9-BTqSHnmdOXzi:-N845A90BEXnGywhr1Bq:bhf2yuo) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/problem_data.h#L64)):*
> ```objc
>   //                                    d(tau_{num_steps-1})/d(q_{num_steps-1})]
>   //
>   std::vector<MatrixXd> dtau_dq;
> ```

mega nit. I was thinking `dtau_dqt` (with extra t) would read better? that way all of these have the same number of characters.
Feel free to ignore if you don't like it.
___
*[`traj_opt/trajectory_optimizer.h` line 127 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N845_K4ADgqpdL4SrKg:-N845_K4ADgqpdL4SrKh:b-dr9xxf) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.h#L127)):*
> ```objc
>    * using finite differences.
>    *
>    * For testing purposes only - this is very inefficient.
> ```

fyi, I am not convinced this is bad. Actually, it might be a real good way to go if you consider that it'd be trivial to parallelize this method using threads.
___
*[`traj_opt/trajectory_optimizer.h` line 149 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N8478UA5wXZx2Ut4Qcf:-N8478UA5wXZx2Ut4Qcg:bu9xl51) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.h#L149)):*
> ```objc
>    * @param tau generalized forces
>    */
>   void InverseDynamicsHelper(const VectorXd& q, const VectorXd& v,
> ```

mega nit. Usually if we use the word "Helper" in a method name probably that indicates a bit of a lack of naming creativity haha.
Here I'd name it to indicate precisely what this method does. E.g. `CalcInverseDynamics()` could be a good name. And along those lines, maybe `CalcTau()`  could be named `CalcInverseDynamicsAtAllTimes()`. That way I don't need to introspect the signature to figure out which one is which.
___
*[`traj_opt/trajectory_optimizer.cc` line 98 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N808z0-A0HB79no_zMo:-N848-PK2uq6uncZXv2q:b-x8dpvw) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/trajectory_optimizer.cc#L98)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

I think it's not worth it for now. Eventually, when `CalcInverseDynamicsPartials` gets called, I believe we will have already computed `q`, `v(q)`, and `tau(q)`. Either for the total cost `L(q)`, the gradient/Hessian, or something else. So I think the better solution would be to pass `tau` as an argument (probably inside some struct), per the TODO in the comment above. 
</blockquote></details>

I like that.
Maybe we could think that the optimizer has a `State`. That state would also contain a `Cache` (not in the Drake sense but more in the sense of a lil struct that stores intermediate compuations). A quick way to write that would be:
```c++
// Struct to store computations that are a function of the state of the solver, the configurations q.
struct Cache {
  std::vector<VectorXd> v;  // N.B. In our method v and a are functions of the state q.  
  std::vector<VectorXd> a;
  std::vector<VectorXd> tau;
  GradientData dtau_dq;
};

struct State {
  // TODO: consider single long vectors for better cache (hardware level) access.
  std::vector<VectorXd> q;  // The only true state of the solver.
  
  // Everything else is a function of q. We put that in the cache.
  mutable Cache cache;
};
```
___
*[`traj_opt/trajectory_optimizer.cc` line 61 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N8470i-1GPyKTHQYnuo:-N8470i-1GPyKTHQYnup:bgnuwdw) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.cc#L61)):*
> ```cpp
>     // All dynamics terms are treated implicitly, i.e.,
>     // tau[t] = M(q[t+1]) * a[t] - k(q[t+1],v[t+1]) - f_ext[t+1]
>     InverseDynamicsHelper(q[t + 1], v[t + 1], a, workspace, &tau->at(t));
> ```

btw, this reads super clear now!
___
*[`traj_opt/trajectory_optimizer.cc` line 118 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N84CiIx905UxAmkWutv:-N84CiIx905UxAmkWutw:bj7p5eq) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.cc#L118)):*
> ```cpp
>   double dqt_i;
>   for (int t = 0; t <= num_steps(); ++t) {
>     for (int i = 0; i < plant().num_positions(); ++i) {
> ```

This took me some thougth really. I like what you did. So that we dont forget the logic, add these docs (or similar):
```c++
// N.B. A perturbation of qt propagates to tau[t-1], tau[t] and tau[t+1]. Therefore we compute one column of  grad_tau at a time.
// That is, once this loop on positions i is over, we effectively computed the t-th column of grad_tau.
```
___
*[`traj_opt/trajectory_optimizer.cc` line 120 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N849bLaDkJSQ67K7Qbv:-N849bLaDkJSQ67K7Qbw:b-9ozct7) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.cc#L120)):*
> ```cpp
>     for (int i = 0; i < plant().num_positions(); ++i) {
>       // Perturb q_t by epsilon
>       q_eps_t = q[t];
> ```

To avoid unnecessary copies, I'd place this outside the loop in comoponents `i`.
Then here you'd only update the i-th component:
```c++
q_eps_t(i) = q[t](i) + dqt_i;

// Perform all computations here....


// Before leaving lets reset that one component only.
q_eps_t(i) = q[t](i);
```



_Code quote:_
```cpp
q_eps_t = q[t];
```
___
*[`traj_opt/trajectory_optimizer.cc` line 123 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N84DJ0d6KKawvKxevSm:-N84DJ0eDcSGfWl5HqwR:bdaekhj) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.cc#L123)):*
> ```cpp
>       dqt_i =
>           eps * std::max(1.0, std::abs(q_eps_t(i)));  // avoid losing precision
>       q_eps_t(i) += dqt_i;
> ```

Following the comment above, if we know the perturbation in qt, namely `dqt_i`, we also know the perturbation in `vt`, it is `dqt_i/time_step`.
Therefore we can perform the same trick on v by updating only the i-th component as (similarly for accelerations):
```c++
  vt_eps = vt; // outside the i-loop.
  vp_eps = vt; // outside the i-loop.

  for (int i = 0; ..... ) [...]

2022-07-28 15:02 UTC, amcastro-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/17)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.cc` line 130 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N84JrRF0YcKVTlavrIz:-N84JrRG2Jh0XrIafHz7:b-zf66e) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.cc#L130)):*
> ```cpp
>         v_eps_t = prob_.v_init;
>       } else {
>         v_eps_t = (q_eps_t - q[t - 1]) / time_step();
> ```

Maybe this changes to:
`if(t > 0) vt_eps(i) += dv_i; ` ?


<!-- Sent from Reviewable.io -->

2022-07-28 18:06 UTC, vincekurtz reviewed
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/17)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @amcastro-tri)

___
*[`traj_opt/problem_data.h` line 37 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N844gba0YPJB3XyA59j:-N84L6vv4PRkYediQ0dn:b-kx1xb) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/problem_data.h#L37)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Following the train of thought for dtau_dqm[0], should we also do `dtau_dqp[num_steps-1].setConstant(nv, nq, NAN)`?
</blockquote></details>

I think that `dtau_dqp[num_steps-1]` = `dtau(T-1)/dq(T)`, which is well-defined. 
___
*[`traj_opt/problem_data.h` line 64 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N845A9-BTqSHnmdOXzi:-N84MCjX8puWltKmnU76:b-4b0c25) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/problem_data.h#L64)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

mega nit. I was thinking `dtau_dqt` (with extra t) would read better? that way all of these have the same number of characters.
Feel free to ignore if you don't like it.
</blockquote></details>

SGTM. I like having all the same number of characters.
___
*[`traj_opt/trajectory_optimizer.cc` line 98 at r2](https://reviewable.io/reviews/vincekurtz/drake/17#-N808z0-A0HB79no_zMo:-N84NvpO4jWLgswPK08z:b-t5jbuc) ([raw file](https://github.com/vincekurtz/drake/blob/6af0e37b533be4f94856a9819f64a0feb286078d/traj_opt/trajectory_optimizer.cc#L98)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I like that.
Maybe we could think that the optimizer has a `State`. That state would also contain a `Cache` (not in the Drake sense but more in the sense of a lil struct that stores intermediate compuations). A quick way to write that would be:
```c++
// Struct to store computations that are a function of the state of the solver, the configurations q.
struct Cache {
  std::vector<VectorXd> v;  // N.B. In our method v and a are functions of the state q.  
  std::vector<VectorXd> a;
  std::vector<VectorXd> tau;
  GradientData dtau_dq;
};

struct State {
  // TODO: consider single long vectors for better cache (hardware level) access.
  std::vector<VectorXd> q;  // The only true state of the solver.
  
  // Everything else is a function of q. We put that in the cache.
  mutable Cache cache;
};
```
</blockquote></details>

I think this is probably a new PR, but I like this idea. 
___
*[`traj_opt/trajectory_optimizer.cc` line 118 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N84CiIx905UxAmkWutv:-N84OW9uDtzYb5nvmcWK:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.cc#L118)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

This took me some thougth really. I like what you did. So that we dont forget the logic, add these docs (or similar):
```c++
// N.B. A perturbation of qt propagates to tau[t-1], tau[t] and tau[t+1]. Therefore we compute one column of  grad_tau at a time.
// That is, once this loop on positions i is over, we effectively computed the t-th column of grad_tau.
```
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 120 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N849bLaDkJSQ67K7Qbv:-N84QEI26GEXfiXHh6fz:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.cc#L120)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

To avoid unnecessary copies, I'd place this outside the loop in comoponents `i`.
Then here you'd only update the i-th component:
```c++
q_eps_t(i) = q[t](i) + dqt_i;

// Perform all computations here....


// Before leaving lets reset that one component only.
q_eps_t(i) = q[t](i);
```


</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 123 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N84DJ0d6KKawvKxevSm:-N84yngW3TrtqZ-T4i_D:br97ffs) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.cc#L123)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Following the comment above, if we know the perturbation in qt, namely `dqt_i`, we also know the perturbation in `vt`, it is `dqt_i/time_step`.
Therefore we can perform the same trick on v by updating only the i-th component as (similarly for accelerations):
```c++
  vt_eps = vt; // outside the i-loop.
  vp_eps = vt; // outside the i-loop.

  for (int i = 0; ..... ) {
    // Before computing tau.
    double dv_i = dqt_i/time_step;
    double da_i = dv_i/time_step;
    
   // Changes in v.
    vt_eps(i) += dv_i;   
    vp_eps(i) -= dv_i;
    
    // Changes in a.  
    am_eps(i) += da_i;
    at_eps(i) -= 2.0 * da_i;   
    ap_eps(i) += da_i;

    // Computations of dtau_dq go here.... 

    // reset this one component only before leaving the i-loop.
    vt_eps(i) = vt[t](i);  
    vp_eps(i) = vt[t](i);  
    am_eps(i) = at[t](i);  
    at_eps(i) = at[t](i);  
    ap_eps(i) = at[t](i);  
  }  // end of i-loop
```


</blockquote></details>

Done, very neat trick. It actually makes a lot of things cleaner.

It also motivates computing `a[t]` ahead of time (we weren't before) as part of some sort of State/Cache thing. Will open another PR to do that. 
___
*[`traj_opt/trajectory_optimizer.cc` line 130 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N84JrRF0YcKVTlavrIz:-N84ynOVBhrAb10dRiMk:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.cc#L130)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Maybe this changes to:
`if(t > 0) vt_eps(i) += dv_i; ` ?

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-28 18:36 UTC, amcastro-tri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/17#-:-N855C7KEkod9cLGjrzk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.cc` line 123 at r3](https://reviewable.io/reviews/vincekurtz/drake/17#-N84DJ0d6KKawvKxevSm:-N852vt-31N4gR08Rjim:b-x6969d) ([raw file](https://github.com/vincekurtz/drake/blob/24f330a654129601404f8dc7766cf2310fe97c1f/traj_opt/trajectory_optimizer.cc#L123)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Done, very neat trick. It actually makes a lot of things cleaner.

It also motivates computing `a[t]` ahead of time (we weren't before) as part of some sort of State/Cache thing. Will open another PR to do that. 
</blockquote></details>

glad you liked it!


<!-- Sent from Reviewable.io -->

2022-07-28 18:41 UTC, merged