Solver draft
vincekurtz/drake pull request #25
Opened 2022-08-04 14:11 UTC by vincekurtz

This is a rough draft of the whole solution pipeline for problems without contact or constraints.

2022-08-09 15:30 UTC, vincekurtz reviewed
+@amcastro-tri for feature review please!

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/25#-:-N92CxPv9Mg31fNkyYIx:b-57wv80)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @amcastro-tri)



<!-- Sent from Reviewable.io -->

2022-08-10 14:22 UTC, amcastro-tri requested changes
First pass. Only the examples. 
Digging into the code now...

> Reviewed 7 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/25#-:-N977gvEDV2QTBJKkKMR:b-asm4fx)* status: 7 of 14 files reviewed, 6 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/solver_parameters.h` line 25 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N977WSh5_nD5Wee_t_1:-N977WSh5_nD5Wee_t_2:b1r343s) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/solver_parameters.h#L25)):*
> ```objc
> 
>   // Flag for whether to print out iteration data
>   bool verbose = true;
> ```

fyi, this makes my runs about 30% slower in my laptop. You might consider setting this to false when making plots.
___
*[`traj_opt/examples/acrobot.cc` line 58 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N96t1WC-Pn6KT_p9vHm:-N96t1WC-Pn6KT_p9vHn:b-quzpf1) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/examples/acrobot.cc#L58)):*
> ```cpp
>  * @param solution_data struct containing iteration and timing data
>  */
> void save_to_csv(const SolutionData<double>& data) {
> ```

nit, consider this being a method of SolutionData? like `SolutionData::SaveToCsv()`, so that you don't need to copy/paste this throughout different examples.
___
*[`traj_opt/examples/acrobot.cc` line 85 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N96tQCs3LIviFB--Z6v:-N96tQCt7pkt95C4lUZH:b-mwyjnw) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/examples/acrobot.cc#L85)):*
> ```cpp
>  * @param time_step time step (seconds) for the discretization
>  */
> void play_back_trajectory(std::vector<VectorXd> q, double time_step) {
> ```

very cool! two suggestions here:
 1. Instead of creating the plant from scratch pass it as an argument. That way you can use exactly the same plant you used for trajopt.
 2. Consider making this a generic method in its own file so that you can use it for all of your examples. It'd seem that's possible?
___
*[`traj_opt/examples/acrobot.cc` line 116 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N96tt8GC3zYmlW7NMjS:-N96tt8GC3zYmlW7NMjT:b-vem7dz) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/examples/acrobot.cc#L116)):*
> ```cpp
> 
>     // Hack to make the playback roughly realtime
>     std::this_thread::sleep_for(std::chrono::duration<double>(time_step));
> ```

nit, suggestion. If you had a `real_time_rate` flag, here you could sleep for `time_step/real_time_rate`, for those cases in which playing more slowly is useful. 
___
*[`traj_opt/examples/acrobot.cc` line 157 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N96uNEn1Xj3nX6kWStS:-N96uNEo1fCFOMiWHvKG:b9tbmiz) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/examples/acrobot.cc#L157)):*
> ```cpp
>     solver_params.linesearch_method = LinesearchMethod::kBacktracking;
>   } else {
>     solver_params.linesearch_method = LinesearchMethod::kArmijo;
> ```

snob nit. Here if I pass `foo`, this code goes with `armijo`. Maybe spell out the "armijo" option and make the default to be throwing an error message.
___
*[`traj_opt/examples/acrobot.cc` line 194 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N96uyH83F_QgI668771:-N96uyH83F_QgI668772:bd6rqj4) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/examples/acrobot.cc#L194)):*
> ```cpp
>       }
>     }
>     std::cout << "Maximum actuated torque: " << max_actuated_torque
> ```

fyi, the quotient `Rᵤ/Rₐ⋅uₐ/uᵤ ≈ 0.32` is pretty much constant for a wide range of values of `Rᵤ/Rₐ`. You might want to print that to the screen aloso.
___
*[`traj_opt/examples/plot_acrobot_data.py` line 17 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N96qPg-E6oTCrtT5nTW:-N96qPg-E6oTCrtT5nTX:bjd4qfq) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/examples/plot_acrobot_data.py#L17)):*
> ```Python
> ##
> 
> drake_root = "/home/vincentkurtz/drake/"
> ```

nit, is there a way to use $PWD so that we avoid having to change this for different users?
___
*[`traj_opt/examples/plot_linesearch_residual.py` line 16 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N96s0iZEznpDng-msN9:-N96s0iZEznpDng-msNA:bhjc72t) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/examples/plot_linesearch_residual.py#L16)):*
> ```Python
> 
> # Get data from the same files
> data_file = drake_root + "bazel-out/k8-opt/bin/traj_opt/examples/acrobot.runfiles/drake/linesearch_data.csv"
> ```

I don't have this file after running the acrobot. Maybe place a comment on how to trigger writing this file?
Maybe even a brief README in you examples directory would help.



_Code quote:_
```Python
"bazel-out/k8-opt/bin/traj_opt/examples/acrobot.runfiles/drake/linesearch_data.csv
```


<!-- Sent from Reviewable.io -->

2022-08-10 15:06 UTC, amcastro-tri requested changes
second pass. Towards the `Solve()` method...

> Reviewed 6 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/25#-:-N97Hmsa4AX8DbmkuFWl:bgc46ts)* status: 13 of 14 files reviewed, 20 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.h` line 37 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97BK8S3t8QQ9fh1ZdG:-N97BK8S3t8QQ9fh1ZdH:b9mbks0) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.h#L37)):*
> ```objc
>    *             etc.
>    * @param params solver parameters, including max iterations, linesearch
>    *               method, etc.
> ```

minor, document what `std::nullopt` means?
If it means "default constructed SolverParameters", then I'd advocate for something like `const SolverParameters& params = SolverParamters{}`, which clearly state that it is not that parameters are optional, but rather we always do need parameters but with optional **values**.
___
*[`traj_opt/trajectory_optimizer.h` line 157 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97BxvDDGUloZODfHcV:-N97BxvDDGUloZODfHcW:b-yfny9x) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.h#L157)):*
> ```objc
>    */
>   void UpdateCacheTrajectoryData(
>       const TrajectoryOptimizerState<T>& state) const;
> ```

fyi, per my comment in this state file, this would nicely ready like `UpdateCacheTrajectoryData(const TrajectoryOptimizerState<T>& state, TrajectoryOptimizerCache<T>::TrajectoryData* trajectory_data)`.
___
*[`traj_opt/trajectory_optimizer.h` line 342 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97D9COAD9FnHKEQ2ox:-N97D9COAD9FnHKEQ2oy:b-1xn9x2) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.h#L342)):*
> ```objc
>    * @param dq search direction, stacked as one large vector
>    * @param g gradient of the overall cost
>    * @param state TrajectoryOptimizerState used for computing L(q + alpha*dq)
> ```

if you see my previous comment in the state.h file, it'd seem to me like this would read nicer if you had something like 
```c++
 std::tuple<double, int> CalcStepLength(const TrajOptimizerState<T>& state, const VectorX<T>& dq, TrajOptimizerState<T>* scratch_state);
```

Notice that cost `L`, gradient `g` and even Hessian `H` are functions of `q`and therefore they could nicely be included in the cache.
Notice also that your documentation gets simpler. You don't need to explain "previous and/or current iteration" stuff. Simply this method takes a state `q` and  direction `dq`  and solves the problem `min_{alpha} L(q + alpha*dq).`.
___
*[`traj_opt/trajectory_optimizer.h` line 360 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97E9-u5mmwz_gVXGSB:-N97E9-u5mmwz_gVXGSC:b-re6x4p) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.h#L360)):*
> ```objc
>    * This allows us to make a nice plot in python after the fact
>    */
>   void SaveLinesearchResidual(const T L, const std::vector<VectorX<T>>& q,
> ```

ditto, here passing a `State&` should be all you need (plus of course the scratch.
___
*[`traj_opt/trajectory_optimizer.h` line 367 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97ENPCE26AVirWaM4a:-N97ENPCE26AVirWaM4b:bb143g6) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.h#L367)):*
> ```objc
>    * Simple backtracking linesearch strategy to find alpha that satisfies
>    *
>    *    L(q + alpha*dq) < L(q) - c*g'*dq
> ```

I believe this is a `+` sign? given that (hopefully) the search direction is a descent direction and therefore the dot product `g'⋅dq` is negative.
___
*[`traj_opt/trajectory_optimizer.h` line 372 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97EFpW05uP9iooq-gq:-N97EFpW05uP9iooq-gr:b-e0e1pg) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.h#L372)):*
> ```objc
>    */
>   std::tuple<double, int> BacktrackingLinesearch(
>       const T L, const std::vector<VectorX<T>>& q, const VectorX<T>& dq,
> ```

ditto on signature.
___
*[`traj_opt/trajectory_optimizer.cc` line 224 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97EpEkBSXSkwMzofjn:-N97EpEl5wTV4_2xuWrH:bbdgqei) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L224)):*
> ```cpp
>       // Make dqt_i exactly representable to minimize floating point error
>       const T temp = q_eps_t(i) + dq_i;
>       dq_i = temp - q_eps_t(i);
> ```

does this help in the end. If so, could you say something about why is it that we don't care making `dv_i` nor `da_i` to be exactly representable?
___
*[`traj_opt/trajectory_optimizer.cc` line 544 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97FHw6EGArNE00eIrI:-N97FHw6EGArNE00eIrJ:b-ozcuxx) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L544)):*
> ```cpp
> 
> template <typename T>
> void TrajectoryOptimizer<T>::AddToQ(const VectorX<T>& dq,
> ```

nit, sonsider making this a method in the state? something like `TrajectoryOptimizerState::SetState(const VectorX<T>& q)`.
___
*[`traj_opt/trajectory_optimizer.cc` line 616 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97Go9499iGFiflXsK3:-N97Go9499iGFiflXsK4:b-upnxjz) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L616)):*
> ```cpp
>   // Exit early with alpha = 1 when we are close to convergence
>   const double convergence_threshold =
>       100 * std::numeric_limits<double>::epsilon();
> ```

ditto here, isn't this too tight?
___
*[`traj_opt/trajectory_optimizer.cc` line 624 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97HERk44412TC4dwQZ:-N97HERk44412TC4dwQ_:b-56j83a) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L624)):*
> ```cpp
>   state->set_q(q);
>   AddToQ(alpha * dq, state);
>   T L_old = CalcCost(*state);
> ```

I'd imagine computing the cost should be cheap when you got a bunch of stuff already in the cache. You might even have computed it before in the outer loop. Consider placing the cost in the cache and having an `EvalCost()` method instead.
___
*[`traj_opt/trajectory_optimizer.cc` line 669 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97Fqxg1HQ45uSl4Cfc:-N97Fqxg1HQ45uSl4Cfd:b-oxfhxx) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L669)):*
> ```cpp
>   const double rho = 0.8;
> 
>   double alpha = 1.0 / rho;        // get alpha = 1 on first iteration
> ```

btw, nice! someone read my code :-)
___
*[`traj_opt/trajectory_optimizer.cc` line 678 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97G9xK2RY6KiWD3eI0:-N97G9xK2RY6KiWD3eI1:b6x2v7o) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L678)):*
> ```cpp
>   // Exit early with alpha = 1 when we are close to convergence
>   const double convergence_threshold =
>       100 * std::numeric_limits<double>::epsilon();
> ```

isn't this too tight? for finite differences doesn't this have an asymptote around 1e-7 or 1e-8? 
___
*[`traj_opt/trajectory_optimizer.cc` line 693 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97Ga6B3KOkpuRi_eLo:-N97Ga6B3KOkpuRi_eLp:b7e8w8m) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L693)):*
> ```cpp
>     state->set_q(q); [...]

2022-08-10 17:20 UTC, amcastro-tri reviewed
This is awesome! great progress! 
Review pass done.

> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/25#-:-N97lMt5Dq7Skpn_wMag:b-dd38fx)* status: all files reviewed (commit messages unreviewed), 24 unresolved discussions (waiting on @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.cc` line 720 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97jS5V5ah1oP7O18yu:-N97jS5V5ah1oP7O18yv:bbutjm1) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L720)):*
> ```cpp
> 
>   // solution_data must be empty
>   DRAKE_DEMAND(solution_data->iteration_times.size() == 0);
> ```

minor, you could have a method `SolutionData::empty()`
___
*[`traj_opt/trajectory_optimizer.cc` line 728 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97khnaAlVhhIxNKsi4:-N97khnaAlVhhIxNKsi5:b-ap3ok) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L728)):*
> ```cpp
>   // Detailed solution data
>   std::vector<double>& iteration_times = solution_data->iteration_times;
>   std::vector<double>& iteration_costs = solution_data->iteration_costs;
> ```

minor, consider having `SolutionData::PushData(time, cost, alpha, ...)` so that minimize the chance of forgetting one of these.
___
*[`traj_opt/trajectory_optimizer.cc` line 773 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97kEvvETOuzbFvD1jl:-N97kEvvETOuzbFvD1jm:b-n3yll7) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L773)):*
> ```cpp
> 
>     // Compute the total cost
>     iteration_costs.push_back(CalcCost(state));
> ```

nit, I'd have an EvalCost() here since it looks like you'll use it later at least within the linesearch.
___
*[`traj_opt/trajectory_optimizer.cc` line 782 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97l7eN4K5qpNrs4JjD:-N97l7eN4K5qpNrs4JjE:b-qf94dr) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L782)):*
> ```cpp
>     dq = -g;
>     PentaDiagonalFactorization Hchol(H);
>     DRAKE_DEMAND(Hchol.status() == PentaDiagonalFactorizationStatus::kSuccess);
> ```

nit, it looks like this `Solve` method is meant to return some failure code when something goes wrong. Here however we decide to abort and break that promise.
Consider instead returning with a status code informing that the factorization failed.


<!-- Sent from Reviewable.io -->

2022-08-10 18:46 UTC, amcastro-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/25)* status: all files reviewed (commit messages unreviewed), 25 unresolved discussions (waiting on @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.cc` line 64 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N9842-M8Z2EqejWrLlJ:-N9842-M8Z2EqejWrLlK:bkb297p) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L64)):*
> ```cpp
>     const std::vector<VectorX<T>>& tau,
>     TrajectoryOptimizerWorkspace<T>* workspace) const {
>   VectorX<T> cost = VectorX<T>::Zero(1);
> ```

`T cost`, no reason to use `VectorX`? (and incur in heap allocation)


<!-- Sent from Reviewable.io -->

2022-08-10 22:17 UTC, vincekurtz reviewed
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/25)* status: 2 of 14 files reviewed, 13 unresolved discussions (waiting on @amcastro-tri)

___
*[`traj_opt/trajectory_optimizer.h` line 342 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97D9COAD9FnHKEQ2ox:-N98gjkJC1RXn5DKmAvk:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.h#L342)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

if you see my previous comment in the state.h file, it'd seem to me like this would read nicer if you had something like 
```c++
 std::tuple<double, int> CalcStepLength(const TrajOptimizerState<T>& state, const VectorX<T>& dq, TrajOptimizerState<T>* scratch_state);
```

Notice that cost `L`, gradient `g` and even Hessian `H` are functions of `q`and therefore they could nicely be included in the cache.
Notice also that your documentation gets simpler. You don't need to explain "previous and/or current iteration" stuff. Simply this method takes a state `q` and  direction `dq`  and solves the problem `min_{alpha} L(q + alpha*dq).`.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.h` line 360 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97E9-u5mmwz_gVXGSB:-N98gd_a-Wv4cDYnJkkC:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.h#L360)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto, here passing a `State&` should be all you need (plus of course the scratch.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.h` line 367 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97ENPCE26AVirWaM4a:-N97oVHg1989PXaYSAKe:b-waclgn) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.h#L367)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I believe this is a `+` sign? given that (hopefully) the search direction is a descent direction and therefore the dot product `g'⋅dq` is negative.
</blockquote></details>

Oops, yup, should be `+`
___
*[`traj_opt/trajectory_optimizer.h` line 372 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97EFpW05uP9iooq-gq:-N98gaeeBclzbqfy4OUb:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.h#L372)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto on signature.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 64 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N9842-M8Z2EqejWrLlJ:-N98fJEZCftKFNuu6PBC:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L64)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

`T cost`, no reason to use `VectorX`? (and incur in heap allocation)
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 224 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97EpEkBSXSkwMzofjn:-N98g-pg2K8KhLPP5oaw:b-dh8hwl) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L224)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

does this help in the end. If so, could you say something about why is it that we don't care making `dv_i` nor `da_i` to be exactly representable?
</blockquote></details>

For the acrobot, this doesn't seem to gain us much, if anything, in precision. Should we still keep it?

For the pendulum without gravity, it seemed like making `dv_i` and `da_i` exactly representable didn't change anything at all - just made the code look more messy. Not sure why that didn't help. 
___
*[`traj_opt/trajectory_optimizer.cc` line 616 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97Go9499iGFiflXsK3:-N98_8bq-z8DoTW0Jnp-:b-437upk) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L616)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ditto here, isn't this too tight?
</blockquote></details>

See other reply
___
*[`traj_opt/trajectory_optimizer.cc` line 624 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97HERk44412TC4dwQZ:-N98_C1n2FzqFtv-fSzk:b-uyb213) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L624)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd imagine computing the cost should be cheap when you got a bunch of stuff already in the cache. You might even have computed it before in the outer loop. Consider placing the cost in the cache and having an `EvalCost()` method instead.
</blockquote></details>

Cost, gradient, and Hessian are now in the cache!
___
*[`traj_opt/trajectory_optimizer.cc` line 678 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97G9xK2RY6KiWD3eI0:-N98ZnZl0OcdLv_o64oz:b-e6d5jg) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L678)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

isn't this too tight? for finite differences doesn't this have an asymptote around 1e-7 or 1e-8? 
</blockquote></details>

The the norm of the gradient (normalized by cost) has an asymptote around 1e-8, but this seems to converge to something considerably smaller. 
___
*[`traj_opt/trajectory_optimizer_state.h` line 22 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97CoBk6L2SpecxXMPT:-N98p58v-tmIQdvpDDbQ:b-slgpvu) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer_state.h#L22)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I haven't seen the rest of the code yet, but I am surprised not to see the gradient and Hessian of the cost here. After all, those are also functions of the solver's state `q`. It might also be much simpler to pass those around in a single state object.
</blockquote></details>

`g` and `H` are now in the cache!
___
*[`traj_opt/examples/acrobot.cc` line 85 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N96tQCs3LIviFB--Z6v:-N97U0BQEBCHBx_duZz5:b-fa9x4s) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/examples/acrobot.cc#L85)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

very cool! two suggestions here:
 1. Instead of creating the plant from scratch pass it as an argument. That way you can use exactly the same plant you used for trajopt.
 2. Consider making this a generic method in its own file so that you can use it for all of your examples. It'd seem that's possible?
</blockquote></details>

1. Can you add the plant to a new diagram, once it's already been constructed and is part of another diagram? The reason is we want the plant to be connected to `DrakeVisualizer` in this playback function, but probably not for trajopt. 
2. Good idea, pending (1). There's a lot of overlap between the examples right now, I'm realizing. 
___
*[`traj_opt/examples/acrobot.cc` line 157 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N96uNEn1Xj3nX6kWStS:-N97TsmWCxIMD9jkBpLd:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/examples/acrobot.cc#L157)):* [...]

2022-08-11 13:47 UTC, vincekurtz reviewed
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/25)* status: 11 of 14 files reviewed, 6 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.h` line 94 at r2](https://reviewable.io/reviews/vincekurtz/drake/25#-N99M6i29k98h2UnYVpJ:-N9BrkhZ0-oRN_LNCRRM:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/84062bbbad1f1a1df9594380f672051d1178e49f/traj_opt/trajectory_optimizer.h#L94)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

There is an `EvalCost()` below. Maybe make this one private then?
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 224 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97EpEkBSXSkwMzofjn:-N9Bv8HS0mWbnoC8J_yE:b-jsjikf) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L224)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

That's ok. But what about `dq_i` for the pendulum and/or acrobot, does the exact representation help? if no, I'd remove. If yes, I'd add note explaining your observations that made you take this decision. 
</blockquote></details>

Doesn't appear to help for either the pendulum or the acrobot, so removed
___
*[`traj_opt/trajectory_optimizer.cc` line 678 at r1](https://reviewable.io/reviews/vincekurtz/drake/25#-N97G9xK2RY6KiWD3eI0:-N9BwOdH1ZFJ0a-CRsP0:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/ce1b6f09ccd4fbd1272b96db3ae5bf97b41a1d2f/traj_opt/trajectory_optimizer.cc#L678)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Interesting. You might consider adding a note here so that we don't forget when we look at this code 6 months later :-) 
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 71 at r2](https://reviewable.io/reviews/vincekurtz/drake/25#-N99Olt50n0_HifX7Nkl:-N9Buc7B2WSBOvvftn0I:b-8tqeci) ([raw file](https://github.com/vincekurtz/drake/blob/84062bbbad1f1a1df9594380f672051d1178e49f/traj_opt/trajectory_optimizer.cc#L71)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

does the compiler really require you to place `[0]` here?
humm... that might be due to Eigen's (overly smart IMO) lazy evaluation.
Also you could write `cost += T(q_err.transpose() * prob_.Qq * q_err)` to force Eigen resolve the computation.
</blockquote></details>

it does require it - replaced with `cost += T(q_err.transpose() * prob_.Qq * q_err)`
___
*[`traj_opt/trajectory_optimizer.cc` line 506 at r2](https://reviewable.io/reviews/vincekurtz/drake/25#-N99QJjd0gBZKs3ouW0h:-N9Bw1EU2yTALb4A2_lE:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/84062bbbad1f1a1df9594380f672051d1178e49f/traj_opt/trajectory_optimizer.cc#L506)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

very minor, consider calling this `CalcCacheTrajectoryData()` for consistency with the rest. That way it's easy to identify the pair EvallFoo()/CalcFoo() for each cached quantity.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-11 13:48 UTC, merged