Add augmented Lagrangian solver to handle unactuation constraints
vincekurtz/drake pull request #35
Opened 2022-08-29 21:58 UTC by aykut-tri

- Adds the augmented Lagrangian (AL) solver described in Framework 17.3 in "Nocedal, J., & Wright, S. J. (2006). Numerical optimization 2nd edition" as an outer loop to handle equality constraints due to underactuation
- Adds options for the proposed method that can be set through the configuration yaml file
- Adds the AL multipliers into the solver state
- Adds a vector of unactuated degrees of freedom into the problem definition
- So far, the proposed method has only been tested for the acrobot example which can be run through: `bazel run traj_opt/examples:acrobot` (the AL solver is enabled for this example but is disabled by default)

2022-08-29 23:00 UTC, vincekurtz requested changes
This looks really promising Aykut, thanks so much for your help on this! The solution quality for the acrobot looks much better than what we were getting before as well, which is great to see.

One thing that would help clean a lot of stuff up: run the lint checks and make sure the unit tests pass with `bazel test //traj_opt/...`. It looks like this broke a few of the unit tests for `CalcCost`, since that function now has additional arguments. 

I did find that I was able to break it by doubling the time horizon to 80 timesteps. Is that because the inner iterations aren't properly converging, and therefore something that should be fixed by having proper convergence criteria?

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/35#-:-NAfkyKB0QASxEVUiSAR:be3etis)* status: all files reviewed, 9 unresolved discussions (waiting on @aykut-tri)

___
*[`traj_opt/problem_definition.h` line 59 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfcAlX6-m7cXw08iO3:-NAfcAlX6-m7cXw08iO4:b-fgiqwc) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/problem_definition.h#L59)):*
> ```objc
> 
>   // Indices of the unactuated DOF
>   std::vector<int> unactuated_dof;
> ```

I think it might be nicer to get this from `plant.MakeActuationMatrix` rather than having the user set it
___
*[`traj_opt/trajectory_optimizer.h` line 227 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfkpAGAOPEu9W31hdJ:-NAfkpAGAOPEu9W31hdK:b-h7oj2w) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer.h#L227)):*
> ```objc
>    *
>    * @param state optimizer state, including q, v, tau, gradients, etc.
>    * @param scratch_state a separate state variable for the linesearch
> ```

`state` and `scratch_state` should be const
___
*[`traj_opt/trajectory_optimizer.h` line 256 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfkfzg3bPYt8-8d-yD:-NAfkfzg3bPYt8-8d-yE:b-h7oj2w) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer.h#L256)):*
> ```objc
>    * @return SolverFlag
>    */
>   SolverFlag SolveWithTrustRegion(TrajectoryOptimizerState<T>& state,
> ```

`state` and `scratch_state` should be const
___
*[`traj_opt/trajectory_optimizer.h` line 321 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfizLZ-xGBriGrieoR:-NAfizLZ-xGBriGrieoS:behmkki) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer.h#L321)):*
> ```objc
> 
>   /**
>    * Compute the vector of forces acting upon unactuated DOF
> ```

nit, since the method name is so general (dealing with any sort of constraint), it seems like the description should be similarly general.
___
*[`traj_opt/trajectory_optimizer_solution.h` line 41 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAffnAqDlKcfNr-wBv-:-NAffnAqDlKcfNr-wBv0:b-139ss4) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer_solution.h#L41)):*
> ```objc
> struct TrajectoryOptimizerStats {
>   // Total solve time
>   std::vector<double> solve_time;
> ```

I'd rather have one double that is the total solve time, and vectors of inner/outer iteration solve times
___
*[`traj_opt/trajectory_optimizer_state.h` line 189 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfgwHKCYXUFsjZ2HXx:-NAfgwHL16REIc0e2amY:b-y1s7gk) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer_state.h#L189)):*
> ```objc
>    *
>    * @param num_steps number of timesteps in the optimization problem
>    * @param params solver parameters
> ```

nit, add brief explanation of this parameter
___
*[`traj_opt/trajectory_optimizer_state.h` line 321 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfhMy-3fwENswzfvtf:-NAfhMy-3fwENswzfvtg:bz5gjrg) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer_state.h#L321)):*
> ```objc
>   }
> 
>   // Set all the cache invalidation flags to false
> ```

I think this should still be private?
___
*[`traj_opt/examples/acrobot.yaml` line 20 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfhniE-sX4kV-boFfx:-NAfhniF0SpvkRJFLzdC:bfncu6d) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/examples/acrobot.yaml#L20)):*
> ```YAML
> 
> # Set the incides of the unactuated degrees of freedom
> unactuated_dof : [0]
> ```

Like comment above, I would rather get this from the plant than have the user specify it. 
___
*[`traj_opt/examples/acrobot.yaml` line 41 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfhcPDDxRnmMkP8JsJ:-NAfhcPDDxRnmMkP8JsK:boshyxl) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/examples/acrobot.yaml#L41)):*
> ```YAML
> proximal_operator : false     # whether to add a proximal operator cost term
> rho_proximal : 1e-8           # the proximal cost multiplier
> # Augmented Lagrangian parameters
> ```

nit, would add a space above this line. 

but also, this looks very cool


<!-- Sent from Reviewable.io -->

2022-08-31 14:22 UTC, aykut-tri reviewed
Vince, thanks very much for your feedback, this is really helpful!

Yeah, the tests, good point! :sweat_smile: I fixed the linting issues and the unit tests. It also helped to identify some other issues in my changes (e.g., not having default values for the AL parameters when not using a yaml config), so thank you!

We definitely need more robust convergence criteria, and I'm thinking about it. But I propose to keep that out of scope of this review. That is, it will require some tuning per example when using the AL solver for now.

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/35#-:-NAoEXi_C2fE_gFz4TQe:b-6591n)* status: 1 of 11 files reviewed, 8 unresolved discussions (waiting on @vincekurtz)

___
*[`traj_opt/problem_definition.h` line 59 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfcAlX6-m7cXw08iO3:-NAjuz185f0UJctbMpso:b-fznoh6) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/problem_definition.h#L59)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

I think it might be nicer to get this from `plant.MakeActuationMatrix` rather than having the user set it
</blockquote></details>

Good idea, done!
___
*[`traj_opt/trajectory_optimizer.h` line 227 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfkpAGAOPEu9W31hdJ:-NAoGQeY4uepRoWvc52f:bn76v00) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer.h#L227)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

`state` and `scratch_state` should be const
</blockquote></details>

They are both manipulated within the solve methods, so can't make them const, but I pass them as pointers now.

The reason for creating the states in the outer loop is to keep track of the AL parameters that are part of the state.
___
*[`traj_opt/trajectory_optimizer.h` line 256 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfkfzg3bPYt8-8d-yD:-NAoGRR1B7H35xaqjSh1:b-mvvp0w) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer.h#L256)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

`state` and `scratch_state` should be const
</blockquote></details>

See my above comment please
___
*[`traj_opt/trajectory_optimizer.h` line 321 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfizLZ-xGBriGrieoR:-NAjxCyW37brb4dEM12t:b-coazba) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer.h#L321)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

nit, since the method name is so general (dealing with any sort of constraint), it seems like the description should be similarly general.
</blockquote></details>

Made the main description more general with a more detailed explanation in parentheses. Please let me know what you think.
___
*[`traj_opt/trajectory_optimizer_solution.h` line 41 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAffnAqDlKcfNr-wBv-:-NAjv8amCE-PJvWujyQF:b-g1hs4j) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer_solution.h#L41)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

I'd rather have one double that is the total solve time, and vectors of inner/outer iteration solve times
</blockquote></details>

Makes sense, done!
___
*[`traj_opt/trajectory_optimizer_state.h` line 189 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfgwHKCYXUFsjZ2HXx:-NAjzCc26Y-D_36k9jGi:bhbwe3c) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer_state.h#L189)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

nit, add brief explanation of this parameter
</blockquote></details>

Is it more clear this way?
___
*[`traj_opt/trajectory_optimizer_state.h` line 321 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfhMy-3fwENswzfvtf:-NAoDrXz-RJuo9ZtfCiv:b-7bcez3) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer_state.h#L321)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

I think this should still be private?
</blockquote></details>

Since the states are now created in the outer loop, this method is used to invalidate anything remaining from the previous major iteration. Hence, it's been made public.
___
*[`traj_opt/examples/acrobot.yaml` line 20 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfhniE-sX4kV-boFfx:-NAjvE44BqbjQLnfTehp:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/examples/acrobot.yaml#L20)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Like comment above, I would rather get this from the plant than have the user specify it. 
</blockquote></details>

Done.
___
*[`traj_opt/examples/acrobot.yaml` line 41 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfhcPDDxRnmMkP8JsJ:-NAjzZqI5iH4YvYr3cn5:b-dtkds3) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/examples/acrobot.yaml#L41)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

nit, would add a space above this line. 

but also, this looks very cool
</blockquote></details>

Done, thanks!


<!-- Sent from Reviewable.io -->

2022-10-05 15:46 UTC, vincekurtz requested changes
Ok, just finished another pass. It look good generally - my main comments are on the use of the state/cache, where there are a few things that could be cleaned up. Let me know if any of that is at all unclear.

> Reviewed 9 of 21 files at r4, 9 of 10 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/35#-:-NDcoLk352rB9w2dYxKT:b-4wpmjy)* status: all files reviewed, 12 unresolved discussions (waiting on @aykut-tri)

___
*[`traj_opt/solver_parameters.h` line 140 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcYd9U6cKSbTPLJa1q:-NDcYd9U6cKSbTPLJa1r:b-nk7d6h) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/solver_parameters.h#L140)):*
> ```objc
>   double lineplot_q_max = 1.0;
> 
>   // Parameters for overwriting unactuated DOF indices
> ```

Why is this necessary? Is it something to do with the fact that `B` is undefined for model instances with no actuation? If so a note of explanation for why this is needed would be nice. 
___
*[`traj_opt/trajectory_optimizer.h` line 321 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfizLZ-xGBriGrieoR:-NDcaH8jDLashpWGbMLX:bsw40y1) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer.h#L321)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Made the main description more general with a more detailed explanation in parentheses. Please let me know what you think.
</blockquote></details>

It does sort of feel like if the goal is any constraint `c(x)=0` then the argument should be `state` rather than `tau`. Otherwise it seems fine
___
*[`traj_opt/trajectory_optimizer.h` line 181 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDc_IkN7Kqp8y3l41Ea:-NDc_IkN7Kqp8y3l41Eb:b-ax0z4x) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.h#L181)):*
> ```objc
>    * Solve the optimization from the given initial guess.
>    *
>    * @param state optimizer state, including q, v, tau, gradients, etc.
> ```

nit, a lot of these things are not arguments of this function
___
*[`traj_opt/trajectory_optimizer.h` line 458 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDc_zSv6bn8ZWypyFrk:-NDc_zSv6bn8ZWypyFrl:b-jz1g7r) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.h#L458)):*
> ```objc
>    */
>   T CalcCost(const std::vector<VectorX<T>>& q, const std::vector<VectorX<T>>& v,
>              const std::vector<VectorX<T>>& tau, const VectorXd& lambda,
> ```

nit, update docstring to reflect these new parameters
___
*[`traj_opt/trajectory_optimizer.cc` line 125 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcb27a1yUSON8_J6MT:-NDcb27a1yUSON8_J6MU:b-vebfhr) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L125)):*
> ```cpp
> 
> template <typename T>
> VectorX<T> TrajectoryOptimizer<T>::CalcConstraintViolations(
> ```

The signature `void TrajectoryOptimizer<T>::CalcConstraintViolations(const std::vector<VectorX<T>>& tau, VectorX<T>* violations)` might be better, to avoid heap allocations.

Actually, a better option would be to store `violations` in the `state`'s cache, similar to what we do with `tau`, `v`, `cost`, etc. Then you'd have an `EvalConstraintViolations(state)` and a `CalcConstraintViolations(state)`, matching the pattern with `EvalCost` and `CalcCost`. Does that make sense? Let me know if it doesn't. 
___
*[`traj_opt/trajectory_optimizer.cc` line 178 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcfQg792wTGuTI0FKg:-NDcfQg84PaA2ItZvEXh:bv82uj9) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L178)):*
> ```cpp
>     TrajectoryOptimizerWorkspace<T>* workspace) const {
>   T cost = 0;
>   T augmented_cost = 0;
> ```

Is this really necessary? Why not just `cost += ...`?
___
*[`traj_opt/trajectory_optimizer.cc` line 2608 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcim6uD5Sb-oha8u9u:-NDcim6uD5Sb-oha8u9v:b6s7qrc) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L2608)):*
> ```cpp
>   // Outer loop
>   for (int i = 0; i < params_.max_major_iterations; ++i) {
>     if (params_.augmented_lagrangian) {
> ```

nit, this flow (enter a loop and break if not using augmented lagrangian) seems kind of awkward to me. Why not something more like
```
if (augmented lagrangian) {
    do the whole loop thing;
} else {
   return SolveGausseNewton(...);
}
```
___
*[`traj_opt/trajectory_optimizer.cc` line 2624 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDciJhA1CVLjNp2yXZN:-NDciJhA1CVLjNp2yXZO:bjfo2ja) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L2624)):*
> ```cpp
>     }
> 
>     // Invalidate the state cache
> ```

per comments on `TrajectoryOptimizerState`, I'd prefer to let the state do the invalidating of the cache when something gets set, and not rely on the caller remembering to do that. 
___
*[`traj_opt/trajectory_optimizer.cc` line 2644 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcjMX88VwqZ8nrIfvL:-NDcjMX88VwqZ8nrIfvM:bsvqrzp) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L2644)):*
> ```cpp
>     // Report constraint violation and final position cost
>     if (params_.verbose)
>       std::cout << "\nMax. violation: " << max_violation
> ```

In line with comment above, this is redundant with an existing printout if we're not using AL
___
*[`traj_opt/trajectory_optimizer_state.h` line 321 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfhMy-3fwENswzfvtf:-NDcdWBWEH7CewjnreUG:b-dp27x2) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer_state.h#L321)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Since the states are now created in the outer loop, this method is used to invalidate anything remaining from the previous major iteration. Hence, it's been made public.
</blockquote></details>

What exactly changes between major iterations that means you need to invalidate the cache? If it's `q`, then the cache should be automatically invalidated. If it's some of the augmented lagrangian parameters (e.g. `mu`), I'd rather make `mu` private and have a `set_mu` public method that automatically invalidates the cache. Basically I don't want the caller to be responsible for remembering to invalidate the cache. The caller should be able to call `state.set_foo(foo)` and `EvalBar(state)` and not worry about which cache entries are valid/invalid and which need to be updated/invalidated
___
*[`traj_opt/trajectory_optimizer_state.h` line 354 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcdJKb6-Hy-DWMMIXP:-NDcdJKc46o21zhObvWh:bt27a6b) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer_state.h#L354)):*
> ```objc
> 
>   // Augmented Lagrangian parameters
>   std::vector<Eigen::VectorXd> lambda_;
> ```

Why do we need a `std::vector` of lambda and mu in the state? Is it just for logging? If so I'd prefer to store that outside the state
___
*[`traj_opt/examples/example_base.cc` line 339 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcmxvc3cwYm-3imbBd:-NDcmxvd1QZZxOJlnIf2:b-idrgy0) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/examples/example_base.cc#L339)):*
> ```cpp
>   // Augmented Lagrangian [...]

2022-10-12 14:00 UTC, aykut-tri reviewed
Your feedback has been very helpful, thank you! I believe I've responded to all your comments.

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/35#-:-NEBRI_C0Swutp9LQCdl:bexam7w)* status: 15 of 29 files reviewed, 11 unresolved discussions (waiting on @vincekurtz)

___
*[`traj_opt/solver_parameters.h` line 140 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcYd9U6cKSbTPLJa1q:-NE6eL4z-1JtR9-k_6gf:b-pra2w7) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/solver_parameters.h#L140)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Why is this necessary? Is it something to do with the fact that `B` is undefined for model instances with no actuation? If so a note of explanation for why this is needed would be nice. 
</blockquote></details>

Yes, exactly. I've just added some explanation here. Thanks.
___
*[`traj_opt/trajectory_optimizer.h` line 321 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfizLZ-xGBriGrieoR:-NE2AqZ53ncBw0Zi4qT0:b8nbk90) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer.h#L321)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

It does sort of feel like if the goal is any constraint `c(x)=0` then the argument should be `state` rather than `tau`. Otherwise it seems fine
</blockquote></details>

Makes sense, done
___
*[`traj_opt/trajectory_optimizer.h` line 181 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDc_IkN7Kqp8y3l41Ea:-NE1sYt37i2R2x_lu0ER:bpi6aau) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.h#L181)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

nit, a lot of these things are not arguments of this function
</blockquote></details>

Oops, that probably happened while resolving the conflicts. Fixed now, thanks.
___
*[`traj_opt/trajectory_optimizer.h` line 458 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDc_zSv6bn8ZWypyFrk:-NE23Qd83cPuyTd_S4HJ:ba3nryv) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.h#L458)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

nit, update docstring to reflect these new parameters
</blockquote></details>

Done. I also updated the cost expression above considering the augmented term.
___
*[`traj_opt/trajectory_optimizer.cc` line 125 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcb27a1yUSON8_J6MT:-NE2QUA75WkHSSebP0Gi:bh050s2) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L125)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

The signature `void TrajectoryOptimizer<T>::CalcConstraintViolations(const std::vector<VectorX<T>>& tau, VectorX<T>* violations)` might be better, to avoid heap allocations.

Actually, a better option would be to store `violations` in the `state`'s cache, similar to what we do with `tau`, `v`, `cost`, etc. Then you'd have an `EvalConstraintViolations(state)` and a `CalcConstraintViolations(state)`, matching the pattern with `EvalCost` and `CalcCost`. Does that make sense? Let me know if it doesn't. 
</blockquote></details>

I've done the first change that you proposed. However, I don't think caching would help in this case since this operation is done only once per major iteration (i.e., no re-evaluation would be eliminated). If there's something that I'm missing, please let me know and I'd be happy to make that change as well.
___
*[`traj_opt/trajectory_optimizer.cc` line 178 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcfQg792wTGuTI0FKg:-NE2SEFe2CC1Yfs27Rv6:b-4m3s2p) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L178)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Is this really necessary? Why not just `cost += ...`?
</blockquote></details>

Not really, I think this was something that I did while debugging and forgot later on. Done, thanks.
___
*[`traj_opt/trajectory_optimizer.cc` line 2608 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcim6uD5Sb-oha8u9u:-NE2YZ3Q-bmRDkxugoPQ:bpi5tqb) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L2608)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

nit, this flow (enter a loop and break if not using augmented lagrangian) seems kind of awkward to me. Why not something more like
```
if (augmented lagrangian) {
    do the whole loop thing;
} else {
   return SolveGausseNewton(...);
}
```
</blockquote></details>

I thought about this (and even did the corresponding changes) but then I realized that I still would like to evaluate and store the final pose cost b/c I find that useful for the comparison vs. the baseline, as I explain in one of my following replies also.

So, re-evaluating the final pose cost in both cases makes the proposed structure less favorable in terms of code length and readability, IMHO. Please let me know if this makes sense to you.
___
*[`traj_opt/trajectory_optimizer.cc` line 2624 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDciJhA1CVLjNp2yXZN:-NE2TVK25dHlbQEDxa5D:b-ff01p7) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L2624)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

per comments on `TrajectoryOptimizerState`, I'd prefer to let the state do the invalidating of the cache when something gets set, and not rely on the caller remembering to do that. 
</blockquote></details>

Good point, I guess I did this just to be on the safe side, without much thinking. So, I removed this and made `invalidate_cache()` a private method again. Thanks.
___
*[`traj_opt/trajectory_optimizer.cc` line 2644 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcjMX88VwqZ8nrIfvL:-NE2UYYq7nB8z1dvxX4L:b-o3xu29) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L2644)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

In line with comment above, this is redundant with an existing printout if we're not using AL
</blockquote></details>

You're right about the maximum violation but we don't evaluate or report the final pose cost, and I think it's useful for comparisons. In addition, the major iteration data saving relies on this.

So, I ended up removing the evaluation and printouts for the maximum actuated and unactuated forces in the example base, as it's already done here. That seems to be more effective in terms of saving some lines as well.

Please let me know if you're happy with this.
___
*[`traj_opt/trajectory_optimizer_state.h` line 321 at r1](https://reviewable.io/reviews/vincekurtz/drake/35#-NAfhMy-3fwENswzfvtf:-NE2vK4Q8vhfidMhve57:b-p7u09m) ([raw file](https://github.com/vincekurtz/drake/blob/e274d42f3a941d259434c320404a870811d2e356/traj_opt/trajectory_optimizer_state.h#L321)):*
Indeed, nothing. And I did this change as I explain in a previous reply:
> Good point, I guess I did this just to be on the safe side, without much thinking. So, I removed this and made `invalidate_cache()` a private method again. Thanks.

So, I don't think we need to additionally make `mu` and `lambda` private with associated set/get methods to invalidate the cache.
___
*[`traj_opt/trajectory_optimizer_state.h` line 354 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcdJKb6-Hy-DWMMIXP:-NE2umGy3Jjjdn-Z7DXa:beq4sy9) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a [...]

2022-10-12 20:11 UTC, vincekurtz requested changes
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> modulo some minor comments. 

Since this is such a large batch of changes let's add +@amcastro-tri for another round of review please!

> Reviewed 14 of 14 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/35#-:-NECoE_eDCbGmngdjD7d:b-z42ujg)* status: all files reviewed, 5 unresolved discussions (waiting on @amcastro-tri and @aykut-tri)

___
*[`traj_opt/trajectory_optimizer.h` line 458 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDc_zSv6bn8ZWypyFrk:-NECiH-C6WvxtFDAdBrN:b-ec019s) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.h#L458)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Done. I also updated the cost expression above considering the augmented term.
</blockquote></details>

Excellent!
___
*[`traj_opt/trajectory_optimizer.cc` line 125 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcb27a1yUSON8_J6MT:-NECijQQDah1E2tNnKe2:b-kvoc5d) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L125)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

I've done the first change that you proposed. However, I don't think caching would help in this case since this operation is done only once per major iteration (i.e., no re-evaluation would be eliminated). If there's something that I'm missing, please let me know and I'd be happy to make that change as well.
</blockquote></details>

That seems fair if we're very confident that we'll only ever evaluate violations once per iteration. The advantage of putting them in the cache would be consistency with the other stuff and a possible future in which we want to evaluate the violations again from somewhere else. I'll defer to the judgement of @amcastro-tri as to whether that's worth it in this case or not. 
___
*[`traj_opt/trajectory_optimizer.cc` line 2608 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcim6uD5Sb-oha8u9u:-NECkjUH1SeLmLgibzRm:bcrzmg7) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L2608)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

I thought about this (and even did the corresponding changes) but then I realized that I still would like to evaluate and store the final pose cost b/c I find that useful for the comparison vs. the baseline, as I explain in one of my following replies also.

So, re-evaluating the final pose cost in both cases makes the proposed structure less favorable in terms of code length and readability, IMHO. Please let me know if this makes sense to you.
</blockquote></details>

It's still not my preferred flow, but it's not a huge difference and I'm willing to live with it. 

Part of my hesitation is that I'm not convinced that "final position cost" is particularly informative. It just depends on so many things (value of Q, Qf, R, etc) that I'm not sure it's a particularly good metric for task completion. But again, it doesn't hurt anything to report it. 
___
*[`traj_opt/trajectory_optimizer.cc` line 2644 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcjMX88VwqZ8nrIfvL:-NECm5e175ehfkY58XJf:bjxo4ji) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L2644)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

You're right about the maximum violation but we don't evaluate or report the final pose cost, and I think it's useful for comparisons. In addition, the major iteration data saving relies on this.

So, I ended up removing the evaluation and printouts for the maximum actuated and unactuated forces in the example base, as it's already done here. That seems to be more effective in terms of saving some lines as well.

Please let me know if you're happy with this.
</blockquote></details>

Seems like a reasonable solution. I would like to see the maximum actuated forces here though, since that gives a rough sense of scale for how small the unactuated forces should be
___
*[`traj_opt/trajectory_optimizer_state.h` line 354 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcdJKb6-Hy-DWMMIXP:-NECmc57CRrlU-V6wuN6:b7l524l) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer_state.h#L354)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Thanks for this very helpful comment. I realized the vectors are only used for logging, as you pointed out, and removed them. I also did some renaming for clarity.
</blockquote></details>

Awesome, I like the new names much better!
___
*[`traj_opt/examples/acrobot.yaml` line 15 at r4](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcXjn5D6pGrIzvQjx7:-NECnPa4CobzC__01ho9:b-tk0e2g) ([raw file](https://github.com/vincekurtz/drake/blob/7432825ff7f435144eb10d166779d3b9abefe39f/traj_opt/examples/acrobot.yaml#L15)):*
<details><summary><i>Previously, aykut-tri (Aykut Onol) wrote…</i></summary><blockquote>

Good point! I've enabled the AL solver w/ favorable parameters found by the analysis per example. To get back to the version w/o the AL solver, the user needs to (i) toggle the R matrices, (ii) comment out the relaxed cost tolerances, and (iii) disable the `augmented_lagrangian` parameter (which has been added as a note in the yaml files as well).
</blockquote></details>

It seems a bit annoying that you need to change three things to switch. I'd rather be able to change just by setting the `augmented_lagrangian` parameter. What would you think of eliminating the other two things by (i) overwritting `R` for the unactuated DoFs when augmented lagrangian is enabled and (ii) introducing different convergence tolerances that are used only when AL is enabled?


<!-- Sent from Reviewable.io -->

2022-10-13 15:34 UTC, aykut-tri reviewed
Some nice suggestions in this round as well, thank you. Ready for a third pass...

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/35#-:-NEGyN-24JYNSFb5Ec3Z:b-uwix1c)* status: 12 of 31 files reviewed, 5 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.cc` line 125 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcb27a1yUSON8_J6MT:-NEGwBrn1QE4eo-CoTjP:bwo0ff3) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L125)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

That seems fair if we're very confident that we'll only ever evaluate violations once per iteration. The advantage of putting them in the cache would be consistency with the other stuff and a possible future in which we want to evaluate the violations again from somewhere else. I'll defer to the judgement of @amcastro-tri as to whether that's worth it in this case or not. 
</blockquote></details>

I feel like we should do that if there's a need for re-evaluation, but agreed on the consistency. Let's see what @amcastro-tri thinks...
___
*[`traj_opt/trajectory_optimizer.cc` line 2608 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcim6uD5Sb-oha8u9u:-NEGwau50BvmZGECvQQ8:b9p29k5) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L2608)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

It's still not my preferred flow, but it's not a huge difference and I'm willing to live with it. 

Part of my hesitation is that I'm not convinced that "final position cost" is particularly informative. It just depends on so many things (value of Q, Qf, R, etc) that I'm not sure it's a particularly good metric for task completion. But again, it doesn't hurt anything to report it. 
</blockquote></details>

The reason I like the final position cost is that it gives a "task performance" that is less sensitive to the model/task than the running costs. I thought about normalizing it by the Qf weights such that we have the units of position in all cases but then ended up normalizing by the initial final position cost per example in the analysis. We could find better alternatives for sure but I think we can keep this until we find a better one.
___
*[`traj_opt/trajectory_optimizer.cc` line 2644 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcjMX88VwqZ8nrIfvL:-NECxZCH2VbDD4qCw_Sz:bm1zgys) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer.cc#L2644)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Seems like a reasonable solution. I would like to see the maximum actuated forces here though, since that gives a rough sense of scale for how small the unactuated forces should be
</blockquote></details>

The maximum joint force per joint is still printed out as well as the indices of the unactuated DOF at the beginning. Do you think that's good enough, or would still like to have the max. actuated forces reported separately?
___
*[`traj_opt/trajectory_optimizer_state.h` line 354 at r7](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcdJKb6-Hy-DWMMIXP:-NEGyJk-BsQ-mw9RDwJ2:b-83sjoh) ([raw file](https://github.com/vincekurtz/drake/blob/5aa1d8b2afb6a7ce76e3dc0c471b21d4031acb78/traj_opt/trajectory_optimizer_state.h#L354)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Awesome, I like the new names much better!
</blockquote></details>

Nice!
___
*[`traj_opt/examples/acrobot.yaml` line 15 at r4](https://reviewable.io/reviews/vincekurtz/drake/35#-NDcXjn5D6pGrIzvQjx7:-NEGvgpM84aCsnuOF3OC:bow1t6t) ([raw file](https://github.com/vincekurtz/drake/blob/7432825ff7f435144eb10d166779d3b9abefe39f/traj_opt/examples/acrobot.yaml#L15)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

It seems a bit annoying that you need to change three things to switch. I'd rather be able to change just by setting the `augmented_lagrangian` parameter. What would you think of eliminating the other two things by (i) overwritting `R` for the unactuated DoFs when augmented lagrangian is enabled and (ii) introducing different convergence tolerances that are used only when AL is enabled?
</blockquote></details>

Yes, yes, and yes! Thanks for the suggestion.


<!-- Sent from Reviewable.io -->

2023-02-14 20:34 UTC, vincekurtz commented
Closing because we have another way of handling underactuation constraints as of #63

2023-02-14 20:34 UTC, closed without merging